version: '3.8'

services:
#  phpmyadmin:
#    image: phpmyadmin:latest
#    hostname: phpmyadmin-1
#    container_name: phpmyadmin-1
#    restart: always
#    ports:
#      - '8082:80'
#    environment:
#      PMA_HOST: mysql-1
#      PMA_PORT: 3306
#      PMA_USER: root
#      PMA_PASSWORD: root
#      PMA_ARBITRARY: 1
#    depends_on:
#      - database
#
#  database:
#    hostname: mysql-1
#    container_name: database
#    image: mysql:8.0
#    environment:
#      MYSQL_ROOT: root
#      MYSQL_ROOT_PASSWORD: root
#    ports:
#      - '4306:3306'
#    volumes:
#      - ./volumes/mysql:/var/lib/mysql

  php:
    hostname: php-1
    container_name: php
    build:
      context: ./docker/php
    ports:
      - '9000:9000'
    volumes:
      - ./backend:/var/www/symfony_docker
#    depends_on:
#      - database

  nginx:
    hostname: nginx-1
    container_name: nginx
    image: nginx:stable-alpine
    ports:
      - '8080:80'
    volumes:
      - ./backend:/var/www/symfony_docker
      - ./docker/nginx/:/etc/nginx/conf.d/ # TODO: investigate how the files are being loaded because I thinks it's acting funny
#    depends_on:
#      - php
#      - database

  vue:
    hostname: vue-1
    container_name: vue
    build:
      context: ./frontend  # Vue Dockerfile location
    ports:
      - '8081:8080'  # Expose Vue app on port 8081
    volumes:
      - ./frontend:/app  # Vue app source code location
    environment:
      - VUE_APP_API_URL=http://php-1:9000  # Updated API endpoint to use new PHP host
#    depends_on:
#      - php