version: '3.8'

services:
  phpmyadmin:
    image: phpmyadmin:latest
    hostname: phpmyadmin-1
    container_name: phpmyadmin-1
    restart: always
    ports:
      - '8082:80'
    environment:
      PMA_HOST: mysql-1
      PMA_PORT: 3306
      PMA_USER: root
      PMA_PASSWORD: root
      PMA_ARBITRARY: 1
    depends_on:
      - database

  database:
    hostname: mysql-1
    container_name: database
    image: mysql:8.0
    environment:
      MYSQL_ROOT: root
      MYSQL_ROOT_PASSWORD: root
    ports:
      - '4306:3306'
    volumes:
      - ./volumes/mysql:/var/lib/mysql

#  php:
#    hostname: php81
#    container_name: php
#    build:
#      context: ./docker/php
#    ports:
#      - '9000:9000'
#    volumes:
#      - ./projects-backend:/var/www/symfony_docker
#    depends_on:
#      - database